#!/bin/sh

sync_qubes_vms_wallclock()
{
    # Sync all VMs based on dom0 clock
    DATE=$(date)
    echo
    echo "Syncing VMs clock to: $DATE"
    qvm-run --all -u root --localcmd="date -u -Iseconds" "qubes.SetDateTime dom0"
    # Then try to sync from the network
    /usr/bin/qvm-sync-clock
}

case "$1" in
        thaw|resume) sync_qubes_vms_wallclock ;;
        # Kill qvm-sync-clock (if running) to not desync time after resume
        suspend|hibernate) 
            killall qvm-sync-clock 2> /dev/null
            exit 0
            ;;
        *) exit 0 ;;
esac
