#!/bin/sh

case "$1" in
    suspend|hibernate)
        qubesd-query -e --fail -c /var/run/qubesd.internal.sock \
            dom0 internal.SuspendPre dom0
        ;;
    resume|thaw)
        qubesd-query -e --fail -c /var/run/qubesd.internal.sock \
            dom0 internal.SuspendPost dom0
        ;;
esac
