#!/bin/bash
set -e -o pipefail
#
# The Qubes OS Project, http://www.qubes-os.org
#
# Copyright (C) 2015  Marek Marczykowski-Górecki <marmarek@invisiblethingslab.com>
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation; either version 2
# of the License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.
#
#

if [ $# -lt 2 ] ; then
    echo usage: $0 'dest_vmname file [file]+'
    exit 1
fi

VM="$1"
shift

TMPDIR=`mktemp -d`
trap 'rm -rf -- "$TMPDIR"' EXIT
RESPONSE=$TMPDIR/response
mkfifo -- "$RESPONSE"

# can't use $@ with --localcmd, and $* would fail on whitespace
/usr/lib/qubes/qfile-dom0-agent "$@" <"$RESPONSE" |
qvm-run --no-gui --pass-io --service -q -a -- "$VM" "qubes.Filecopy" >"$RESPONSE"

if [ "${0##*/}" = "qvm-move-to-vm" ]; then
	rm -rf -- "$@"
fi
